name:                okapi
version:             0.2.0.0
github:              "monadicsystems/okapi"
license:             BSD3
author:              "Monadic Systems LLC"
maintainer:          "tech@monadic.systems"
copyright:           "2022 Monadic Systems LLC"
category:            "Web"
synopsis:            "A micro web framework based on monadic parsing"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/monadicsystems/okapi#readme>

dependencies:
- aeson >= 1.4.7
- attoparsec
- base >= 4.7 && < 5
- base64
- bytestring
- containers
- cookie
- cryptonite
- extra
- http-api-data
- http-types
- memory
- mmorph
- mtl
- network
- parser-combinators
- pretty-simple
- text
- transformers
- unagi-chan
- vault
- wai
- wai-extra
- wai-websockets
- warp
- warp-tls
- websockets

library:
  source-dirs: src

executables:
  # realworld-json-exe:
  #   main:                Main.hs
  #   source-dirs:         examples/realworld-json
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - okapi
  #   - containers
  #   - hasql
  #   - hasql-th
  #   - jwt
  #   - parser-combinators
  #   - time
  #   - vector
  #   - profunctors
  realworld-htmx-exe:
    main:                Main.hs
    source-dirs:         examples/realworld-htmx
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - rel8
    - lucid2-htmx
    - lucid2
  calculator-exe:
    main:                Main.hs
    source-dirs:         examples/calculator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
  calculator2-exe:
    main:                Main.hs
    source-dirs:         examples/calculator2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - aeson
    - parser-combinators
    - http-types
    - http-api-data
    - text
  todo-exe:
    main:                Main.hs
    source-dirs:         examples/todo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - sqlite-simple
  todo2-exe:
    main:                Main.hs
    source-dirs:         examples/todo2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - sqlite-simple
  todo3-exe:
    main:                Main.hs
    source-dirs:         examples/todo3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - sqlite-simple    
    - text
    - bytestring
    - interpolatedstring-perl6
  car-dealership-exe:
    main:                Main.hs
    source-dirs:         examples/car-dealership
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - sqlite-simple
    - text
    - bytestring
    - interpolatedstring-perl6
    - parser-combinators
    - random
  # chess-exe:
  #   main:                Main.hs
  #   source-dirs:         examples/chess
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - okapi
  #   - aeson
  #   - bytestring
  #   - extra
  #   - interpolatedstring-perl6
  #   - http-api-data 
  #   - lucid
  #   - lucid-htmx
  #   - text
  #   - time
  #   - slave-thread
  #   - stm
  #   - unagi-chan
  #   - containers
  #   - parser-combinators
  # servant-exe:
  #   main:                Main.hs
  #   source-dirs:         examples/servant
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - okapi
  #   - lucid
  #   - parser-combinators
  #   - servant
  #   - servant-lucid
  #   - servant-server
  sse-exe:
    main:                Main.hs
    source-dirs:         examples/sse
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - slave-thread
    - time
    - bytestring
  static-exe:
    main:                Main.hs
    source-dirs:         examples/static
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
  twitter-clone-exe:
    main:                Main.hs
    source-dirs:         examples/twitter-clone
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - rel8
  dotodo-exe:
    main:                Main.hs
    source-dirs:         examples/dotodo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - sqlite-simple
    - lucid2-htmx
    - lucid2

tests:
  okapi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - doctest-parallel
